<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.
/* Copyright (C) 2026 DaniMarqz. GPL-3.0-or-later; see LICENSE. */
/**
 * Moodle-origin launch page for a Rise/SCORM iframe share.
 *
 * The page intentionally requires the Moodle web session.  The public iframe
 * URL identifies a class and authorization group, but never carries a Moodle
 * identity or watermark data; this page resolves those locally and emits a
 * short-lived signed player token.
 *
 * @package filter_impronta

 * @copyright  2026 DaniMarqz
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

require_once(__DIR__ . '/../../config.php');

use filter_impronta\player;
use filter_impronta\config;
use filter_impronta\request;
use filter_impronta\token;

require_login();

/**
 * Ends the SCORM request with an error.
 * @param int $status HTTP status.
 * @param string $message Error message.
 */
function impronta_scorm_fail(int $status, string $message): void {
    http_response_code($status);
    header('Content-Type: text/plain; charset=utf-8');
    echo $message;
    exit;
}

if (isguestuser()) {
    impronta_scorm_fail(403, get_string('scormguest', 'filter_impronta'));
}

$rawf = optional_param('f', '', PARAM_RAW_TRIMMED);
$group = optional_param('g', '', PARAM_ALPHANUMEXT);
// Accept links generated by an older webapp while keeping g canonical.
if ($group === '') {
    $group = optional_param('group', '', PARAM_ALPHANUMEXT);
}

$path = trim(preg_replace('#/+#', '/', str_replace('\\', '/', (string) $rawf)), '/');
if ($path === '' || strpos($path, '..') !== false) {
    impronta_scorm_fail(400, get_string('missingfilename', 'filter_impronta'));
}
if ($group === '' || !preg_match('/^[A-Za-z0-9_-]{4,128}$/', $group)) {
    impronta_scorm_fail(400, get_string('scormgroupinvalid', 'filter_impronta'));
}

try {
    $playbackid = bin2hex(random_bytes(16));
} catch (\Throwable $e) {
    impronta_scorm_fail(503, get_string('servicedown', 'filter_impronta'));
}

$expires = time() + config::token_ttl();
$userid = (int) $USER->id;
$playbacktoken = token::generate(
    $path,
    $expires,
    0,
    request::ip(),
    $userid,
    false,
    $group,
    $playbackid,
    'scorm'
);

header('Content-Type: text/html; charset=utf-8');
header('Cache-Control: no-store, private');

$html = player::render($path, [
    'courseid' => 0,
    'forceplayer' => true,
    'token' => $playbacktoken,
    'expires' => $expires,
    'userid' => $userid,
    'authorizationgroupid' => $group,
    'playbackid' => $playbackid,
    'mode' => 'scorm',
]);

echo '<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" '
    . 'content="width=device-width,initial-scale=1"><title>Impronta</title></head><body>'
    . $html . '</body></html>';
